micronaut:
  application:
    name: backendia
  server:
    port: 8080

  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      payload:
        username-key: email
        password-key: password
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        issuer: "com.fit.auth"
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:12312312312312312312312312312312}
        generator:
          refresh-token:
            enabled: true
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:12312312312312312312312312312312}
reactor:
  enable-automatic-context-propagation: false

datasources:
  default:
    enabled: false
flyway:
  enabled: false