micronaut:
  application:
    name: backendia
  server:
    port: 8080

  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      payload:
        username-key: email
        password-key: password
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        issuer: "com.fit.auth"
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:12312312312312312312312312312312}
        generator:
          refresh-token:
            enabled: true
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:12312312312312312312312312312312}
reactor:
  enable-automatic-context-propagation: false

datasources:
  default:
    url: jdbc:mysql://localhost:3306/exercicio-fit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 124578
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 10

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

#datasources:
#  default:
#    url: "jdbc:mysql:///back-prod-teste?cloudSqlInstance=gen-lang-client-0004040174:us-west1:back-prod-teste&socketFactory=com.google.cloud.sql.mysql.SocketFactory"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: "124578Fe&"
#    dialect: MYSQL
#    db-configs:
#      max-lifetime: 1800000 # 30 min
#      idle-timeout: 600000  # 10 min
#      connection-timeout: 30000